<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>MobileApp.Desktop</AssemblyName>
    <ApplicationIcon>..\MobileApp\Assets\AppIcon\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MobileApp\MobileApp.csproj" />
    <ProjectReference Include="..\..\Rayo.Hosting.Desktop\Rayo.Hosting.Desktop.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\MobileApp\Assets\AppIcon\AppIcon.png" Link="Assets\AppIcon\AppIcon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
