<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    <RootNamespace>Nano</RootNamespace>
    <AssemblyName>Nano</AssemblyName>
    <RayoVersion>0.1.10</RayoVersion>
    <SourceGeneratorNamespace>$(RootNamespace).Extensions</SourceGeneratorNamespace>
    <HotReloadEnabled Condition="'$(Configuration)' == 'Debug'">true</HotReloadEnabled>
    <HotReloadSupported Condition="'$(Configuration)' == 'Debug'">true</HotReloadSupported>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="RootNamespace" />
    <CompilerVisibleProperty Include="SourceGeneratorNamespace" />
    <Compile Remove="Generated\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Rayo\Rayo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LuaCSharp" Version="0.5.5" />
    <PackageReference Include="Silk.NET.SDL" Version="2.23.0" />
    <PackageReference Include="SoundFlow" Version="1.4.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <EmbeddedResource Include="Assets\game.nn" LogicalName="Nano.Assets.game.nn" />
  </ItemGroup>

  <Target Name="BuildDebugGameArchive"
          BeforeTargets="BeforeBuild"
          Condition="'$(Configuration)' == 'Debug'">
    <ZipDirectory SourceDirectory="$(MSBuildProjectDirectory)\Assets\game"
                  DestinationFile="$(MSBuildProjectDirectory)\Assets\game.nn"
                  Overwrite="true" />
  </Target>

</Project>
