namespace Arkanoid;

using Arkanoid.Game;
using Rayo.Animation;
using Rayo.Core;
using Rayo.Core.Input;
using Rayo.Core.Interfaces;
using Rayo.Reactivity;
using Rayo.Rendering;
using System.Numerics;

/// <summary>
/// Rayo visual element that hosts the Arkanoid game.
/// This is where the [ReactiveClass] fluent API belongs — it configures the
/// appearance of the canvas control itself (background, HUD colors, font sizes).
/// Input is handled via IInputHandler; the game loop drives IFrameAnimation.
/// IFocusable ensures clicking on the canvas grants keyboard focus instead of clearing it.
/// IPointerHandler ensures plain mouse moves (no button held) also move the paddle.
/// </summary>
public class ArkanoidCanvas : View<ArkanoidCanvas>,
    IInputHandler,
    IFocusable,
    IPointerHandler,
    IFrameAnimation
{
    // IFocusable — required so EventManager routes keyboard events here after a click.
    public bool IsFocused { get; set; }

    // IPointerHandler — plain mouse move (no button held) tracks the paddle.
    public void OnPointerEntered(PointerEventArgs args) { }
    public void OnPointerExited(PointerEventArgs args) { }
    public void OnPointerMoved(PointerEventArgs args) => MovePaddleToMouse(args.Position.X);
    public void OnPointerPressed(PointerEventArgs args) { }
    public void OnPointerReleased(PointerEventArgs args) { }
    // ── Reactive UI properties (fluent setters generated by [ReactiveClass]) ──

    public Color BackgroundColor { get; set; } = new Color(15, 12, 30);

    public Color WallColor { get; set; } = new Color(50, 50, 80);

    public Color HudColor { get; set; } = new Color(200, 200, 220);

    public float HudFontSize { get; set; } = 16f;

    public float OverlayFontSize { get; set; } = 32f;

    // ── Game ──────────────────────────────────────────────────────────────────

    private readonly ArkanoidGame _game = new();
    private bool _initialized;

    // ── FPS tracking ──────────────────────────────────────────────────────────
    private float _fpsTimer;
    private int _fpsFrameCount;
    private int _currentFps;
    private bool _showFps = false;

    // ── Input state ───────────────────────────────────────────────────────────
    private bool _keyLeft;
    private bool _keyRight;
    private bool _keyLaunch;       // sustained state (true while key/button held)
    private bool _launchRequested; // edge-trigger latch: survives same-frame KeyDown+KeyUp

    // ── IInputHandler ─────────────────────────────────────────────────────────

    public bool CanHandleInput => true;

    public bool HandleInput(InputEventArgs args)
    {
        switch (args.EventType)
        {
            case InputEventType.KeyDown:
            case InputEventType.KeyRepeat:
                switch (args.KeyCode)
                {
                    case InputKey.Left:  _keyLeft   = true;  return true;
                    case InputKey.Right: _keyRight  = true;  return true;
                    case InputKey.Space:
                        _keyLaunch = true;
                        _launchRequested = true;
                        return true;
                    case InputKey.R:
                        _game.RestartGame(); return true;
                    case InputKey.Return when _game.IsWon:
                        _game.NextLevel(); return true;
                }
                break;

            case InputEventType.KeyUp:
                switch (args.KeyCode)
                {
                    case InputKey.Left:  _keyLeft   = false; return true;
                    case InputKey.Right: _keyRight  = false; return true;
                    case InputKey.Space: _keyLaunch = false; return true;
                    case InputKey.F12 : _showFps = !_showFps; return true;
                }
                break;

            case InputEventType.MouseDown:
                _keyLaunch = true;
                _launchRequested = true;
                MovePaddleToMouse(args.Position.X);
                return true;

            case InputEventType.MouseUp:
                _keyLaunch = false;
                return true;

            case InputEventType.MouseMove:
            case InputEventType.MouseDrag:
                MovePaddleToMouse(args.Position.X);
                return true;
        }
        return false;
    }

    private void MovePaddleToMouse(float mouseX)
    {
        if (_game.Paddle == null) return;
        float localX = mouseX - ComputedX;
        float targetX = localX - _game.Paddle.Width / 2f;
        _game.Paddle.Position = new System.Numerics.Vector2(
            Math.Clamp(targetX, 0f, _game.WorldWidth - _game.Paddle.Width),
            _game.Paddle.Position.Y);
    }

    // ── IFrameAnimation ───────────────────────────────────────────────────────

    void IFrameAnimation.Tick(float deltaTime)
    {
        EnsureInitialized();
        _game.SetInput(_keyLeft, _keyRight, _keyLaunch || _launchRequested);
        _launchRequested = false; // consumed — cleared after every tick
        _game.Update(deltaTime);

        // Update FPS
        _fpsFrameCount++;
        _fpsTimer += deltaTime;
        if (_fpsTimer >= 1.0f)
        {
            _currentFps = _fpsFrameCount;
            _fpsFrameCount = 0;
            _fpsTimer -= 1.0f;
        }

        // Force continuous rendering for games - mark tree as needing render
        MarkNeedsPaint();
        UIApplication.Current?.Tree?.MarkNeedsRender();
    }

    // ── Rayo lifecycle ────────────────────────────────────────────────────

    protected override void OnMounted()
    {
        FrameAnimationTicker.Register(this);
        EnsureInitialized();
        UIApplication.Current?.EventManager?.SetFocus(this);

        // Request continuous rendering to prevent idle mode throttling
        if (UIApplication.Current?.Tree != null)
        {
            UIApplication.Current.Tree.MarkNeedsRender();
        }
    }

    protected override void OnUnmounted()
    {
        FrameAnimationTicker.Unregister(this);
    }

    private void EnsureInitialized()
    {
        if (!_initialized && ComputedWidth > 0 && ComputedHeight > 0)
        {
            _game.Initialize(ComputedWidth, ComputedHeight);
            _initialized = true;
        }
    }

    public override void Measure(float availableWidth, float availableHeight)
    {
        DesiredWidth  = float.IsPositiveInfinity(availableWidth)  ? 0 : availableWidth;
        DesiredHeight = float.IsPositiveInfinity(availableHeight) ? 0 : availableHeight;
    }

    public override void Arrange(float x, float y, float width, float height)
    {
        base.Arrange(x, y, width, height);

        if (_initialized)
            _game.Resize(width, height);
        else
            EnsureInitialized();
    }

    // ── Rendering ─────────────────────────────────────────────────────────────

    public override void Render(IRenderer renderer)
    {
        float ox = ComputedX;
        float oy = ComputedY;
        float w  = ComputedWidth;
        float h  = ComputedHeight;

        // Background
        renderer.DrawRect(ox, oy, w, h, BackgroundColor);

        // Subtle grid
        DrawGrid(renderer, ox, oy, w, h);

        // Wall borders (top, left, right)
        renderer.DrawRect(ox,       oy,       w,    4f,  WallColor);   // top
        renderer.DrawRect(ox,       oy,       4f,   h,   WallColor);   // left
        renderer.DrawRect(ox + w - 4f, oy,   4f,   h,   WallColor);   // right

        // Game objects
        _game.World.Render(renderer, ox, oy);

        // HUD
        DrawHud(renderer, ox, oy, w);

        // Overlay messages
        DrawOverlay(renderer, ox, oy, w, h);
    }

    private void DrawGrid(IRenderer renderer, float ox, float oy, float w, float h)
    {
        var gridColor = new Color(255, 255, 255, 8);
        float step = 40f;
        for (float gx = ox; gx < ox + w; gx += step)
            renderer.DrawLine(gx, oy, gx, oy + h, 1f, gridColor);
        for (float gy = oy; gy < oy + h; gy += step)
            renderer.DrawLine(ox, gy, ox + w, gy, 1f, gridColor);
    }

    private void DrawHud(IRenderer renderer, float ox, float oy, float w)
    {
        // Score (left)
        renderer.DrawText($"SCORE  {_game.Score:D6}", ox + 10f, oy + 8f, HudColor, HudFontSize);

        // Lives (right)
        string livesText = $"LIVES  {_game.Lives}";
        var textSize = renderer.MeasureText(livesText, HudFontSize);
        renderer.DrawText(livesText, ox + w - textSize.X - 10f, oy + 8f, HudColor, HudFontSize);

        // Level (center)
        string levelText = $"LEVEL  {_game.Level}";
        var levelSize = renderer.MeasureText(levelText, HudFontSize);
        renderer.DrawText(levelText, ox + (w - levelSize.X) / 2f, oy + 8f, HudColor, HudFontSize);

        // FPS (top right, below lives)
        if (_showFps)
        {
            string fpsText = $"FPS  {_currentFps}";
            var fpsSize = renderer.MeasureText(fpsText, HudFontSize);
            renderer.DrawText(fpsText, ox + w - fpsSize.X - 10f, oy + 8f + HudFontSize + 4f, HudColor, HudFontSize);
        }
    }

    private void DrawOverlay(IRenderer renderer, float ox, float oy, float w, float h)
    {
        if (_game.Phase == GamePhase.WaitingToStart)
        {
            DrawCenteredText(renderer, "SPACE or CLICK to launch", ox, oy, w, h,
                new Color(180, 180, 200), HudFontSize, yOffset: 40f);
            return;
        }

        if (_game.IsGameOver)
        {
            DrawDimOverlay(renderer, ox, oy, w, h);
            DrawCenteredText(renderer, "GAME OVER", ox, oy, w, h,
                new Color(230, 60, 60), OverlayFontSize, yOffset: -24f);
            DrawCenteredText(renderer, $"Score: {_game.Score}", ox, oy, w, h,
                HudColor, HudFontSize, yOffset: 16f);
            DrawCenteredText(renderer, "Press R to restart", ox, oy, w, h,
                new Color(160, 160, 180), HudFontSize, yOffset: 44f);
            return;
        }

        if (_game.IsWon)
        {
            DrawDimOverlay(renderer, ox, oy, w, h);
            DrawCenteredText(renderer, "LEVEL COMPLETE!", ox, oy, w, h,
                new Color(80, 220, 120), OverlayFontSize, yOffset: -24f);
            DrawCenteredText(renderer, $"Score: {_game.Score}", ox, oy, w, h,
                HudColor, HudFontSize, yOffset: 16f);
            DrawCenteredText(renderer, "Press ENTER for next level  |  R to restart", ox, oy, w, h,
                new Color(160, 160, 180), HudFontSize, yOffset: 44f);
        }
    }

    private static void DrawDimOverlay(IRenderer renderer, float ox, float oy, float w, float h)
        => renderer.DrawRect(ox, oy, w, h, new Color(0, 0, 0, 160));

    private void DrawCenteredText(IRenderer renderer, string text,
        float ox, float oy, float w, float h, Color color, float fontSize, float yOffset = 0f)
    {
        var size = renderer.MeasureText(text, fontSize);
        float tx = ox + (w - size.X) / 2f;
        float ty = oy + (h - size.Y) / 2f + yOffset;
        renderer.DrawText(text, tx, ty, color, fontSize);
    }
}
